/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-09 18:22:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BasicServlet.*;

public final class add10_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Add Other Details</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./downloadedStyles/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

HttpSession s= request.getSession(true);
Employee emp=(Employee) s.getAttribute("emp");
String start=(String) s.getAttribute("start");
String end=(String) s.getAttribute("end");
s.setAttribute("add",1);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction DispRows(x){\r\n");
      out.write("\t\tdocument.getElementById(x+\"L\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(x+\"I\").style.display=\"block\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addRow(id, tableID) {  \r\n");
      out.write("        var table = document.getElementById(tableID);  \r\n");
      out.write("        var rowCount = table.rows.length;\r\n");
      out.write("        var tableLength = rowCount+1;\r\n");
      out.write("        var row = table.insertRow(rowCount);\r\n");
      out.write("        \r\n");
      out.write("        var cell0 = row.insertCell(0);\r\n");
      out.write("        var cell1 = row.insertCell(1);\r\n");
      out.write("        var cell2 = row.insertCell(2);\r\n");
      out.write("        var cell3 = row.insertCell(3);\r\n");
      out.write("\r\n");
      out.write("\t\tcell0.setAttribute('width',\"8%\");\r\n");
      out.write("\t\tcell1.setAttribute('width',\"2%\");\r\n");
      out.write("\t\tcell2.setAttribute('width',\"75%\");\r\n");
      out.write("\r\n");
      out.write("        cell0.innerHTML = tableLength; \r\n");
      out.write("        cell1.innerHTML = \":\";\r\n");
      out.write("        \r\n");
      out.write("        var element2 = document.createElement(\"textarea\");\r\n");
      out.write("        element2.setAttribute('placeholder', \"Some Text...\");\r\n");
      out.write("        element2.setAttribute('value', '');\r\n");
      out.write("        element2.setAttribute('required', '');\r\n");
      out.write("        element2.setAttribute('name', 'inputData'+id+tableLength);\r\n");
      out.write("        cell2.appendChild(element2);\r\n");
      out.write("        \r\n");
      out.write("        var element3 = document.createElement(\"input\");\r\n");
      out.write("        element3.type=\"hidden\";\r\n");
      out.write("        element3.setAttribute('name', 'inputFlag'+id+tableLength);\r\n");
      out.write("        \r\n");
      out.write("        if(id==\"1\"){\r\n");
      out.write("        \telement3.setAttribute('value','DRAWING_DETAILS');\r\n");
      out.write("        }\r\n");
      out.write("        else if(id==\"2\"){\r\n");
      out.write("        \telement3.setAttribute('value','WORK_DETAILS');\r\n");
      out.write("        }\r\n");
      out.write("        else if(id==\"3\"){\r\n");
      out.write("        \telement3.setAttribute('value','RESEARCH');\r\n");
      out.write("        }\r\n");
      out.write("        else if(id==\"4\"){\r\n");
      out.write("        \telement3.setAttribute('value','INT_TECH');\r\n");
      out.write("        }\r\n");
      out.write("        else if(id==\"5\"){\r\n");
      out.write("        \telement3.setAttribute('value','TECH_DETAILS');\r\n");
      out.write("        }\r\n");
      out.write("        else{\r\n");
      out.write("        \telement3.setAttribute('value','INPUT_PROJECT');\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        cell2.appendChild(element3);\r\n");
      out.write("        \r\n");
      out.write("        var element4 = document.createElement(\"input\");  \r\n");
      out.write("        element4.type = \"button\";\r\n");
      out.write("        element4.name = \"button\"+tableLength;\r\n");
      out.write("        element4.setAttribute('value', 'Delete');\r\n");
      out.write("        element4.onclick = function () { removeRow(id, \"button\"+tableLength); }\r\n");
      out.write("        cell3.appendChild(element4);\r\n");
      out.write("    }\r\n");
      out.write("    function removeRow(id,btnName) { \r\n");
      out.write("        try {\r\n");
      out.write("\t\t\tconsole.log(btnName);\r\n");
      out.write("            var table = document.getElementById('dataTable'+id);\r\n");
      out.write("            var rowCount = table.rows.length;\r\n");
      out.write("            var tableLength = rowCount+1;\r\n");
      out.write("            for(var i = 0; i < rowCount; i++){\r\n");
      out.write("                var row = table.rows[i];\r\n");
      out.write("                var rowObj = row.cells[3].childNodes[0];\r\n");
      out.write("                if (rowObj.name == btnName) {\r\n");
      out.write("                    table.deleteRow(i);\r\n");
      out.write("                    for(var j=i;j<rowCount-1;j++){\r\n");
      out.write("              \t\t\ttable.rows[j].cells[0].innerHTML=j+1;\r\n");
      out.write("              \t\t}\r\n");
      out.write("                    break;\r\n");
      out.write("                }  \r\n");
      out.write("            }  \r\n");
      out.write("        }  \r\n");
      out.write("        catch (e) {  \r\n");
      out.write("            alert(e);\r\n");
      out.write("        }  \r\n");
      out.write("    }  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\" style=\"margin: auto; width:90%;\">\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<legend>Details of meetings attended during the month</legend>\r\n");
      out.write("\t\t<div style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t<input type=\"hidden\" value=");
      out.print(start );
      out.write(" id=\"start\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" value=");
      out.print(end );
      out.write(" id=\"end\"/>\r\n");
      out.write("            <form action=\"home.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<b>Details of DWGs generated during the month</b><br><br>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div class=\"boxed\" id=\"1L\" onclick=\"DispRows('1')\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Add\" src=\"Add.png\" width=\"80px\" height=\"80px\" style=\"float:left;\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<b>Add Rows</b>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"1I\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"tab\" id=\"dataTable1\" style=\"width:100%;\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"8%\">1</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"75%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea placeholder=\"Some Text...\" name=\"inputData11\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"inputFlag11\" value=\"DRAWING_DETAILS\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"button\" name=\"button1\" value=\"Delete\" onclick=\"removeRow('1','button1')\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t            <input type=\"button\" id=\"add\" value=\"Add Row\" style=\"float:right;\" onclick=\"addRow('1','dataTable1')\" />\r\n");
      out.write("\t\t\t            <br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<b>Details of administrative work done during the month</b><br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div class=\"boxed\" id=\"2L\" onclick=\"DispRows('2')\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Add\" src=\"Add.png\" width=\"80px\" height=\"80px\" style=\"float:left;\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<b>Add Rows</b>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"2I\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"tab\" id=\"dataTable2\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"8%\">1</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"75%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea placeholder=\"Some Text...\" name=\"inputData21\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"inputFlag21\" value=\"WORK_DETAILS\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"button\" class=\"del\" name=\"button1\" value=\"Delete\" onclick=\"removeRow('2','button1')\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t            <input type=\"button\" id=\"add\" value=\"Add Row\" style=\"float:right;\" onclick=\"addRow('2','dataTable2')\" />\r\n");
      out.write("\t\t\t            <br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<b>Details of research work done on the topic assigned to you</b><br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div class=\"boxed\" id=\"3L\" onclick=\"DispRows('3')\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Add\" src=\"Add.png\" width=\"80px\" height=\"80px\" style=\"float:left;\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<b>Add Rows</b>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"3I\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"tab\" id=\"dataTable3\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"8%\">1</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"75%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea placeholder=\"Some Text...\" name=\"inputData31\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"inputFlag31\" value=\"RESEARCH\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"button\" class=\"del\" name=\"button1\" value=\"Delete\" onclick=\"removeRow('3','button1')\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t            <input type=\"button\" id=\"add\" value=\"Add Row\" style=\"float:right;\" onclick=\"addRow('3','dataTable3')\" />\r\n");
      out.write("\t\t\t            <br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<b>Details of internal technical work review</b><br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div class=\"boxed\" id=\"4L\" onclick=\"DispRows('4')\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Add\" src=\"Add.png\" width=\"80px\" height=\"80px\" style=\"float:left;\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<b>Add Rows</b>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"4I\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"tab\" id=\"dataTable4\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"8%\">1</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"75%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea placeholder=\"Some Text...\" name=\"inputData41\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"inputFlag41\" value=\"INT_TECH\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"button\" class=\"del\" name=\"button1\" value=\"Delete\" onclick=\"removeRow('4','button1')\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t            <input type=\"button\" id=\"add\" value=\"Add Row\" style=\"float:right;\" onclick=\"addRow('4','dataTable4')\" />\r\n");
      out.write("\t\t\t            <br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<b>Details of technical work done during the month</b><br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div class=\"boxed\" id=\"5L\" onclick=\"DispRows('5')\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Add\" src=\"Add.png\" width=\"80px\" height=\"80px\" style=\"float:left;\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<b>Add Rows</b>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"5I\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"tab\" id=\"dataTable5\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"8%\">1</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"75%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea placeholder=\"Some Text...\" name=\"inputData51\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"inputFlag51\" value=\"TECH_DETAILS\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"button\" class=\"del\" name=\"button1\" value=\"Delete\" onclick=\"removeRow('5','button1')\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t            <input type=\"button\" id=\"add\" value=\"Add Row\" style=\"float:right;\" onclick=\"addRow('5','dataTable5')\" />\r\n");
      out.write("\t\t\t            <br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<b>Details of any input awaited from project</b><br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div class=\"boxed\" id=\"6L\" onclick=\"DispRows('6')\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Add\" src=\"Add.png\" width=\"80px\" height=\"80px\" style=\"float:left;\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<b>Add Rows</b>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"6I\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"tab\" id=\"dataTable6\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"8%\">1</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"75%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea placeholder=\"Some Text...\" name=\"inputData61\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"inputFlag61\" value=\"INPUT_PROJECT\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"button\" class=\"del\" name=\"button1\" value=\"Delete\" onclick=\"removeRow('6','button1')\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t            <input type=\"button\" id=\"add\" value=\"Add Row\" style=\"float:right;\" onclick=\"addRow('6','dataTable6')\" />\r\n");
      out.write("\t\t\t            <br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("            <input type=\"hidden\" value=\"add10\" name=\"add10\"/>\r\n");
      out.write("            <input type=\"submit\" value=\"Save\"/>\r\n");
      out.write("            </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
