/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-08 12:21:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BasicServlet.*;
import java.sql.*;

public final class directorHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');\r\n");
      out.write("\r\n");
      out.write("\t* {\r\n");
      out.write("\t\t/* margin: 0;\r\n");
      out.write("\t\tpadding: 0;*/\r\n");
      out.write("\t\t/* box-sizing: border-box;  */\r\n");
      out.write("\t\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("body{\r\n");
      out.write("\tbackground: #eddeff\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("\t\t\tbackground: #eddeff\r\n");
      out.write("\t\t}\r\n");
      out.write("\tinput[type=submit]{\r\n");
      out.write("\t\t\tbackground-color: #555555;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\theight:40px;\r\n");
      out.write("\t\t\tborder:none;\r\n");
      out.write("\t\t\tcolor:whitesmoke;\r\n");
      out.write("\t\t\tfont-size: medium;\r\n");
      out.write("\t\t\t/* padding: 15px; */\r\n");
      out.write("\t\t\tbox-shadow: 0 0 7px 0 #000;\r\n");
      out.write("\t\t\t/* padding-bottom: 20px; */\r\n");
      out.write("\t\t\tpadding-left: 15px;\r\n");
      out.write("\t\t\tpadding-right: 15px;\r\n");
      out.write("\t\t\tmargin: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.div-table-row input[type=submit]{\r\n");
      out.write("\t\t\tbackground-color: #555555;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t\tborder:none;\r\n");
      out.write("\t\t\tcolor:whitesmoke;\r\n");
      out.write("\t\t\tfont-size: medium;\r\n");
      out.write("\t\t\t/* padding: 15px; */\r\n");
      out.write("\t\t\tbox-shadow: 0 0 7px 0 #000;\r\n");
      out.write("\t\t\t/* padding-bottom: 20px; */\r\n");
      out.write("\t\t\tpadding-left: 15px;\r\n");
      out.write("\t\t\tpadding-right: 15px;\r\n");
      out.write("\t\t\tmargin: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tinput[type=button]{\r\n");
      out.write("\t\t\tbackground-color: #555555;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t\tborder:none;\r\n");
      out.write("\t\t\tcolor:whitesmoke;\r\n");
      out.write("\t\t\tfont-size: medium;\r\n");
      out.write("\t\t\t/* padding: 15px; */\r\n");
      out.write("\t\t\tbox-shadow: 0 0 7px 0 #000;\r\n");
      out.write("\t\t\t/* padding-bottom: 20px; */\r\n");
      out.write("\t\t\tpadding-left: 15px;\r\n");
      out.write("\t\t\tpadding-right: 15px;\r\n");
      out.write("\t\t\tmargin: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.card {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\theight: auto;\r\n");
      out.write("\t\t\tpadding: 40px 30px;\r\n");
      out.write("\t\t\tbox-shadow: 0 0 10px 0 #000;\r\n");
      out.write("\t\t\t/* position: relative; */\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\tmargin: 15px 15px;\r\n");
      out.write("\t\t}\r\n");
      out.write(".div-table {\r\n");
      out.write("  display: table;         \r\n");
      out.write("  width: auto;     \r\n");
      out.write("  margin: auto;            \r\n");
      out.write("font-size: large;\r\n");
      out.write("\tmax-height: 250px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\toverflow-y: auto;\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".div-table-row {\r\n");
      out.write("  display: table-row;\r\n");
      out.write("  width: auto;\r\n");
      out.write("  clear: both;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  font-size: large;\r\n");
      out.write("}\r\n");
      out.write(".div-table-col {\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-size: large;\r\n");
      out.write("border: 0.5px solid rgb(139, 137, 137);  float: left;\r\n");
      out.write("  display: table-column;\r\n");
      out.write("  height:40px;   \r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  align-items: center;  \r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  align-content: center;\r\n");
      out.write("  flex-direction: column; \r\n");
      out.write("}\r\n");
      out.write(".div-table-col-head{\r\n");
      out.write("\theight: 55px;\r\n");
      out.write("\tborder: 0.5px solid rgb(139, 137, 137);\r\n");
      out.write("  background: #36304a;\r\n");
      out.write("  color: whitesmoke;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  float: left;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("  display: table-column; \r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  align-content: center;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("input[type=text]{\r\n");
      out.write("\tfont-size: large;\r\n");
      out.write("}\r\n");
      out.write("p{\r\n");
      out.write("\tfont-size:20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t#logout{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\ttop: 5%;\r\n");
      out.write("\t\tright: 5%;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=submit]{\r\n");
      out.write("\t\t\tbackground-color: #555555;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\theight:40px;\r\n");
      out.write("\t\t\tborder:none;\r\n");
      out.write("\t\t\tcolor:whitesmoke;\r\n");
      out.write("\t\t\tfont-size: medium;\r\n");
      out.write("\t\t\t/* padding: 15px; */\r\n");
      out.write("\t\t\tbox-shadow: 0 0 7px 0 #000;\r\n");
      out.write("\t\t\t/* padding-bottom: 20px; */\r\n");
      out.write("\t\t\tpadding-left: 15px;\r\n");
      out.write("\t\t\tpadding-right: 15px;\r\n");
      out.write("\t\t\tmargin: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.card {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\theight: auto;\r\n");
      out.write("\t\t\tpadding: 40px 30px;\r\n");
      out.write("\t\t\tbox-shadow: 0 0 10px 0 #000;\r\n");
      out.write("\t\t\t/* position: relative; */\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\tmargin: 15px 15px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.tab{\r\n");
      out.write("\t\t\tborder: 0.5px solid rgb(139, 137, 137);\r\n");
      out.write("\t\t\tfont-size: large;\r\n");
      out.write("\t\t\tmax-height: 250px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\toverflow-y: auto;\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttable, th, td {\r\n");
      out.write("\t\t\tborder: 0.5px solid rgb(139, 137, 137);\r\n");
      out.write("\t\t\tborder-collapse: collapse;\r\n");
      out.write("\t\t\tpadding: 15px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("table thead tr {\r\n");
      out.write("  height: 60px;\r\n");
      out.write("  background: #36304a;\r\n");
      out.write("  color: whitesmoke;\r\n");
      out.write("}\r\n");
      out.write("tbody tr:nth-child(even) {\r\n");
      out.write("  background-color: #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#snackbar,#snackbar1 {\r\n");
      out.write("  visibility: hidden;\r\n");
      out.write("  min-width: 250px;\r\n");
      out.write("  float:right;\r\n");
      out.write("  background-color: rgb(75, 74, 74);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  right:5%;\r\n");
      out.write("  bottom: 30px;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#snackbar.show,#snackbar1.show {\r\n");
      out.write("  visibility: visible;\r\n");
      out.write("  -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;\r\n");
      out.write("  animation: fadein 0.5s, fadeout 0.5s 2.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes fadein {\r\n");
      out.write("  from {bottom: 0; opacity: 0;} \r\n");
      out.write("  to {bottom: 30px; opacity: 1;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes fadein {\r\n");
      out.write("  from {bottom: 0; opacity: 0;}\r\n");
      out.write("  to {bottom: 30px; opacity: 1;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes fadeout {\r\n");
      out.write("  from {bottom: 30px; opacity: 1;} \r\n");
      out.write("  to {bottom: 0; opacity: 0;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes fadeout {\r\n");
      out.write("  from {bottom: 30px; opacity: 1;}\r\n");
      out.write("  to {bottom: 0; opacity: 0;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul li::before {\r\n");
      out.write("  content: \"\\2022\";\r\n");
      out.write("  color: red;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  display: inline-block; \r\n");
      out.write("  width: 1em;\r\n");
      out.write("  margin-left: -1em;\r\n");
      out.write("font-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li button {\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("\tcolor: inherit;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\toutline: inherit;\r\n");
      out.write("  margin-bottom: 2%;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  margin-left: 0.5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"myFunction()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");

HttpSession s= request.getSession(true);
Employee emp=(Employee) s.getAttribute("emp");
String period=(String)request.getParameter("month");
if(period!=null){
	s.setAttribute("period",period);
}
else{
	period=(String)s.getAttribute("period");
}

DNET DNet=new DNET();
Connection dbConnection=DNet.getSurveyThinConnection();
PreparedStatement pStatement;



ResultSet res=null;
try{
	pStatement=dbConnection.prepareStatement("SELECT F_CPERSNO, F_VC2NAME FROM "+DNet.Employee+" WHERE F_VC2DIVISION=?");
	pStatement.setString(1, emp.division);
	res=pStatement.executeQuery();
} catch (SQLException e){
	e.printStackTrace();
}
int i=1;

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction myFunction() {\r\n");
      out.write("\t\tdocument.getElementById('mth1').value=document.getElementById('mth').value;\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"display: flex;\">\r\n");
      out.write("<div class=\"card\" style=\"width: 15%;float:left;\">\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t<img src=\"icon.png\" width=\"80%\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"border-top: 0.5px solid rgb(133, 128, 128);\"></div>\r\n");
      out.write("\t<div style=\"text-align: center;margin-top: 10px;\">\r\n");
      out.write("\t\t<b>");
      out.print( emp.name);
      out.write("</b>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t<form id=\"mnth\" action=\"directorHome.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"month\" id=\"mth\" name=\"month\" onblur=\"document.getElementById('mnth').submit()\" onchange=\"document.getElementById('mnth').submit()\" value= ");
      out.print(period );
      out.write(" required/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"card\" style=\"width:60%; float:left;\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h2><b>\r\n");
      out.write("\t\t\tDetails\r\n");
      out.write("\t\t</b></h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<table class=\"tab\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"30%\">Persno</th>\r\n");
      out.write("\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( emp.persno);
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"30%\">Name</th>\r\n");
      out.write("\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( emp.name );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"30%\">Designation</th>\r\n");
      out.write("\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( emp.designation );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"30%\">Division</th>\r\n");
      out.write("\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( emp.division );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"clear: both;\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\" id=\"display\" style=\"width:85%;height: auto; margin:auto;overflow:auto;max-height:800px;\">\r\n");
      out.write("\t<fieldset style=\"height: 100%; overflow: auto;\">\r\n");
      out.write("\t\t<legend style=\"font-weight: bold;font-size: large;\">List of Employees</legend>\r\n");
      out.write("\t\t<div class=\"div-table\" id=\"dataTable\">\r\n");
      out.write("\t\t\t<div class=\"div-table-row\" id=\"head\">\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:8%\">Sr. No.</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:30%\">Employee ID</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:40%\">Employee Name</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\"  style=\"width:20%\">Report</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
while(res!=null && res.next()){ 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"div-table-row\">\r\n");
      out.write("\t\t\t<form action=\"reportGen.jsp\" method=\"post\"  target=\"_blank\">\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\"  style=\"width:8%\">");
      out.print(i );
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:30%\">\r\n");
      out.write("\t\t\t\t\t<p>");
      out.print(res.getString("F_CPERSNO") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value='");
      out.print(res.getString("F_CPERSNO") );
      out.write("' name=\"persNo\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:40%\">\r\n");
      out.write("\t\t\t\t\t<p>");
      out.print(res.getString("F_VC2NAME") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value='");
      out.print(res.getString("F_VC2NAME") );
      out.write("' name=\"empName\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:20%\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"month\" id=\"mnth1\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"director\" name=\"reportType\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"View\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
i++; 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"logout\">\r\n");
      out.write("<form action=\"login.jsp\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"logout\" name=\"logout\"/>\r\n");
      out.write("\t<input type=\"submit\" value=\"Logout\"/>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
 dbConnection.close(); 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
