/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-09 18:25:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BasicServlet.*;
import java.sql.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./downloadedStyles/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"myFunction()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");

HttpSession s= request.getSession(true);
Employee emp=(Employee) s.getAttribute("emp");
String period=(String)request.getParameter("month");
if(period!=null){
	s.setAttribute("period",period);
}
else{
	period=(String)s.getAttribute("period");
}
String start=null,end=null;
if(period!=null){
	int month=Integer.parseInt(period.substring(5));
	int year=Integer.parseInt(period.substring(0, 4));
	int daysInMonth = month != 2 ? 
			  31 - (((month - 1) % 7) % 2) : 
			  28 + (year % 4 == 0 ? 1 : 0) - (year % 100 == 0 ? 1 : 0) + (year % 400 == 0 ? 1 : 0);
	start=period+"-01";
	end=period+"-"+String.format("%02d", daysInMonth);
}
s.setAttribute("start", start);
s.setAttribute("end", end);
DNET DNet=new DNET();
Connection dbConnection=DNet.getSurveyThinConnection();
PreparedStatement pStatement;

if(request.getParameter("add1")!=null){
	int i=1;
	String no=request.getParameter("no"+i);
	while(no!=null) {
		String date=request.getParameter("date"+i);
		String title=request.getParameter("title"+i);
		try {
			pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_Reports+" VALUES(?,TO_DATE(?,'YYYY/MM/DD'),?,?)");
			pStatement.setString(1,emp.persno);
			pStatement.setString(2,date);
			pStatement.setString(3,no);
			pStatement.setString(4,title);
			pStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		i++;
		no=request.getParameter("no"+i);
	}
}


if(request.getParameter("add2")!=null){
	int i=1;
	String jour=request.getParameter("jour"+i);
	while(jour!=null) {
		String date=request.getParameter("date"+i);
		String title=request.getParameter("title"+i);
		try {
			pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_Papers+" VALUES(?,TO_DATE(?,'YYYY/MM/DD'),?,?)");
			pStatement.setString(1,emp.persno);
			pStatement.setString(2,date);
			pStatement.setString(3,title);
			pStatement.setString(4,jour);
			pStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		i++;
		jour=request.getParameter("jour"+i);
	}
}


if(request.getParameter("add3")!=null){
	int i=1;
	String from=request.getParameter("from"+i);
	while(from!=null) {
		String to=request.getParameter("to"+i);
		String title=request.getParameter("title"+i);
		try {
			pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_Cep+" VALUES(?,TO_DATE(?,'YYYY/MM/DD'),TO_DATE(?,'YYYY/MM/DD'),?)");
			pStatement.setString(1,emp.persno);
			pStatement.setString(2,from);
			pStatement.setString(3,to);
			pStatement.setString(4,title);
			pStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		i++;
		from=request.getParameter("from"+i);
	}
}

if(request.getParameter("add4")!=null){
	int i=1;
	String tcd=request.getParameter("dt"+i);
	while(tcd!=null) {
		String title=request.getParameter("title"+i);
		try {
			pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_TC+" VALUES(?,TO_DATE(?,'YYYY/MM/DD'),?)");
			pStatement.setString(1,emp.persno);
			pStatement.setString(2,tcd);
			pStatement.setString(3,title);
			pStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		i++;
		tcd=request.getParameter("dt"+i);
	}
}


if(request.getParameter("add5")!=null){
	int i=1;
	String from=request.getParameter("from"+i);
	while(from!=null) {
		String to=request.getParameter("to"+i);
		String place=request.getParameter("place"+i);
		String purpose=request.getParameter("purpose"+i);
		try {
			pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_TD+" VALUES(?,TO_DATE(?,'YYYY/MM/DD'),TO_DATE(?,'YYYY/MM/DD'),?,?)");
			pStatement.setString(1, emp.persno);
			pStatement.setString(2, from);
			pStatement.setString(3, to);
			pStatement.setString(4, place);
			pStatement.setString(5, purpose);
			pStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		i++;
		from=request.getParameter("from"+i);
	}
}

if(request.getParameter("add6")!=null){
	int i=1;
	String from=request.getParameter("from"+i);
	while(from!=null) {
		String to=request.getParameter("to"+i);
		String nature=request.getParameter("nature"+i);
		try {
			pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_Leaves+" VALUES(?,TO_DATE(?,'YYYY/MM/DD'),TO_DATE(?,'YYYY/MM/DD'),?)");
			pStatement.setString(1, emp.persno);
			pStatement.setString(2, from);
			pStatement.setString(3, to);
			pStatement.setString(4, nature);
			pStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		i++;
		from=request.getParameter("from"+i);
	}
}


if(request.getParameter("add7")!=null){
	int i=1;
	String name=request.getParameter("name"+i);
	while(name!=null) {
		String date=request.getParameter("date"+i);
		String purpose=request.getParameter("purpose"+i);
		try {
			pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_FabricationVisits+" VALUES(?,TO_DATE(?,'YYYY/MM/DD'),?,?)");
			pStatement.setString(1,emp.persno);
			pStatement.setString(2,date);
			pStatement.setString(3,name);
			pStatement.setString(4,purpose);
			pStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		i++;
		name=request.getParameter("name"+i);
	}
}


if(request.getParameter("add8")!=null){
	int i=1;
	String name=request.getParameter("name"+i);
	while(name!=null) {
		String date=request.getParameter("date"+i);
		String purpose=request.getParameter("purpose"+i);
		try {
			pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_Meetings+" VALUES(?,TO_DATE(?,'YYYY/MM/DD'),?,?)");
			pStatement.setString(1,emp.persno);
			pStatement.setString(2,date);
			pStatement.setString(3,name);
			pStatement.setString(4,purpose);
			pStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		i++;
		name=request.getParameter("name"+i);
	}
}


if(request.getParameter("add9")!=null){
	int i=1;
	String projectName=request.getParameter("projectName"+i);
	while(projectName!=null) {
		String projectDesc=request.getParameter("projectDesc"+i);
		String status=request.getParameter("status"+i);
		String PDC=request.getParameter("PDC"+i);
		try {
			pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_WorkProgress+" VALUES(?,TO_DATE(?,'YYYY-MM'),?,?,?,TO_DATE(?,'YYYY/MM/DD'))");
			pStatement.setString(1,emp.persno)
;			pStatement.setString(2, period);
			pStatement.setString(3,projectName);
			pStatement.setString(4,projectDesc);
			pStatement.setString(5,status);
			pStatement.setString(6,PDC);
			pStatement.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		i++;
		projectName=request.getParameter("projectName"+i);
	}
}

if(request.getParameter("add10")!=null){
	for(int j=1;j<7;j++){
		int i=1;
		String inputData=request.getParameter("inputData"+j+""+i);
		while(inputData!=null) {
			String inputFlag=request.getParameter("inputFlag"+j+""+i);
			try {
				pStatement=dbConnection.prepareStatement("INSERT INTO "+DNet.MPR_All+" VALUES(?,TO_DATE(?,'YYYY-MM'),?,?)");
				pStatement.setString(1, emp.persno);
				pStatement.setString(2, period);
				pStatement.setString(3, inputData);
				pStatement.setString(4, inputFlag);
				pStatement.executeUpdate();
			} catch (SQLException e) {
				e.printStackTrace();
			}
			i++;
			inputData=request.getParameter("inputData"+j+""+i);
		}
	}
}


ResultSet res1=null;
try{
	pStatement=dbConnection.prepareStatement("SELECT REP_NO, TO_CHAR(REP_DATE, 'dd/mm/yyyy') as REPD, TITLE FROM "+DNet.MPR_Reports+" WHERE F_CPERSNO=? AND TO_CHAR(REP_DATE,'YYYY-MM') LIKE ? ORDER BY REP_DATE");
	pStatement.setString(1, emp.persno); 
	pStatement.setString(2, period);
	res1=pStatement.executeQuery();
} catch (SQLException e){
	e.printStackTrace();
}

ResultSet res2=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TITLE, JOUR_NAME, TO_CHAR(PAPER_DATE, 'dd/mm/yyyy') AS PPD FROM "+DNet.MPR_Papers+" WHERE F_CPERSNO=? AND TO_CHAR(PAPER_DATE,'YYYY-MM') LIKE ? ORDER BY PAPER_DATE");
	pStatement.setString(1, emp.persno);  
	pStatement.setString(2, period);
	res2=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res3=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TO_CHAR(FROM_DATE, 'dd/mm/yyyy') AS FMD, TO_CHAR(TO_DATE, 'dd/mm/yyyy') AS TOD, TITLE FROM "+DNet.MPR_Cep+" WHERE F_CPERSNO=? AND TO_CHAR(FROM_DATE,'YYYY-MM') LIKE ? ORDER BY FROM_DATE");
	pStatement.setString(1, emp.persno);  
	pStatement.setString(2, period);
	res3=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res4=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TO_CHAR(TC_DATE, 'dd/mm/yyyy') AS TCD, TITLE FROM "+DNet.MPR_TC+" WHERE F_CPERSNO=? AND TO_CHAR(TC_DATE,'YYYY-MM') LIKE ? ORDER BY TC_DATE");
	pStatement.setString(1, emp.persno);  
	pStatement.setString(2, period);
	res4=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res5=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TO_CHAR(FROM_DATE, 'dd/mm/yyyy') AS FMD, TO_CHAR(TO_DATE, 'dd/mm/yyyy') AS TOD, PLACE, PURPOSE FROM "+DNet.MPR_TD+" WHERE F_CPERSNO=? AND TO_CHAR(FROM_DATE,'YYYY-MM') LIKE ? ORDER BY FROM_DATE");
	pStatement.setString(1, emp.persno);  
	pStatement.setString(2, period);
	res5=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res6=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TO_CHAR(FROM_DATE, 'dd/mm/yyyy') AS FMD, TO_CHAR(TO_DATE, 'dd/mm/yyyy') AS TOD, LEAVE_TYPE FROM "+DNet.MPR_Leaves+" WHERE F_CPERSNO=? AND TO_CHAR(FROM_DATE,'YYYY-MM') LIKE ? ORDER BY FROM_DATE");
	pStatement.setString(1, emp.persno);  
	pStatement.setString(2, period);
	res6=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res7=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT INDUSTRY, TO_CHAR(VISIT_DATE, 'dd/mm/yyyy') as VISD, PURPOSE FROM "+DNet.MPR_FabricationVisits+" WHERE F_CPERSNO=? AND TO_CHAR(VISIT_DATE,'YYYY-MM') LIKE ? ORDER BY VISIT_DATE");
	pStatement.setString(1, emp.persno);  
	pStatement.setString(2, period);
	res7=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res8=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT PROJECT_NAME, TO_CHAR(MEETING_DATE, 'dd/mm/yyyy') as MD, PURPOSE FROM "+DNet.MPR_Meetings+" WHERE F_CPERSNO=? AND TO_CHAR(MEETING_DATE,'YYYY-MM') LIKE ? ORDER BY MEETING_DATE");
	pStatement.setString(1, emp.persno);  
	pStatement.setString(2, period);
	res8=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res9=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT PROJECT_NAME, TO_CHAR(PDC, 'dd/mm/yyyy') AS PCD, DESCRIPTION, STATUS FROM "+DNet.MPR_WorkProgress+" WHERE F_CPERSNO=? AND TO_CHAR(WP_DATE, 'yyyy-mm') LIKE ? ORDER BY PDC");
	pStatement.setString(1, emp.persno);  
	pStatement.setString(2, period);
	res9=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res10=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT * FROM "+DNet.MPR_All+" WHERE F_CPERSNO=? AND TO_CHAR(FDATE,'YYYY-MM') LIKE ? ORDER BY FDATE", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
	pStatement.setString(1, emp.persno);  
	pStatement.setString(2, period);
	res10=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
int i=1;

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction myFunction() {\r\n");
      out.write("\t\tvar Tables = document.getElementsByClassName(\"tabDiv\");\r\n");
      out.write("\t\tfor (var i=0; i<Tables.length; i++){\r\n");
      out.write("\t\t\tvar rowCount = Tables[i].getElementsByTagName(\"table\")[0].rows.length;\r\n");
      out.write("\t\t\tif(rowCount<2){\r\n");
      out.write("\t\t\t\tTables[i].getElementsByTagName(\"div\")[0].style.display = \"block\";\r\n");
      out.write("\t\t\t\tTables[i].getElementsByTagName(\"div\")[0].textContent = \"No data to show\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.getElementById(\"toast\")!=null){\r\n");
      out.write("\t\t\tvar x = document.getElementById(\"snackbar\");\r\n");
      out.write("\t\t\tx.className = \"show\";\r\n");
      out.write("\t\t\tsetTimeout(function(){ x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.getElementById(\"toast1\")!=null){\r\n");
      out.write("\t\t\tvar x = document.getElementById(\"snackbar1\");\r\n");
      out.write("\t\t\tx.className = \"show\";\r\n");
      out.write("\t\t\tsetTimeout(function(){ x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction options(x){\r\n");
      out.write("\t\tvar element=document.getElementById('display');\r\n");
      out.write("\t\tif(document.getElementById('mth').value==''){\r\n");
      out.write("\t\t\talert('Enter month');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tif(element.style.display='none'){\r\n");
      out.write("\t\t\t\telement.style.display='block';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telement.innerHTML = document.getElementById(x).innerHTML;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"display: flex;\">\r\n");
      out.write("<div class=\"card\" style=\"width: 15%;float:left;\">\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t<img src=\"icon.png\" width=\"80%\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"border-top: 0.5px solid rgb(133, 128, 128);\"></div>\r\n");
      out.write("\t<div style=\"text-align: center;margin-top: 10px;\">\r\n");
      out.write("\t\t<b>");
      out.print( emp.name);
      out.write("</b>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t<form id=\"mnth\" action=\"home.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"month\" id=\"mth\" name=\"month\" onblur=\"document.getElementById('mnth').submit()\" onchange=\"document.getElementById('mnth').submit()\" value= ");
      out.print(period );
      out.write(" required/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"card\" style=\"width:60%; float:left;\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h2><b>\r\n");
      out.write("\t\t\tDetails\r\n");
      out.write("\t\t</b></h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<table class=\"tab\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"30%\">Persno</th>\r\n");
      out.write("\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( emp.persno);
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"30%\">Name</th>\r\n");
      out.write("\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( emp.name );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"30%\">Designation</th>\r\n");
      out.write("\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( emp.designation );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"30%\">Division</th>\r\n");
      out.write("\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( emp.division );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"clear: both;\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("\t<div class=\"card\" style=\"width:18%; height:auto; float:left; padding:20px 20px 20px 20px;\">\r\n");
      out.write("\t\t<fieldset style=\"float:left\">\r\n");
      out.write("\t\t\t<legend>Options</legend>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('1')\">Nos. of reports generated during the month with list</button></li>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('2')\">Title of research paper submitted</button></li>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('3')\">Details of CEP/ Conference/ Lectures attended during the month</button></li>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('4')\">Details of TC/any presentations you have made last</button></li>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('5')\">Details of TDs during the month</button></li>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('6')\">Details of leave taken during the month</button></li>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('7')\">Visits to Fabrication agencies during the month</button></li>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('8')\">Details of meetings attended during the month</button></li>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('9')\">Details of work in Progress</button></li>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<li><button onclick=\"options('10')\">Other</button></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"card\" id=\"display\" style=\"width:65%; max-height:800px; float:left; display:none;\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\" id=\"1\" style=\"width:70%; max-height:800px; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Nos. of reports generated during the month</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<table class=\"tab\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"4%\">Sr. No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Report No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Title</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res1!=null && res1.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res1.getString("REP_NO") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res1.getString("REPD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res1.getString("TITLE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add1.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd1.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"card\" id=\"2\" style=\"width:65%; max-height:800px; float:left; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Title of research paper submitted</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<table class=\"tab\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"4%\">Sr. No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Title of Research Paper</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Journal/ Conference name</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Dates</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res2!=null && res2.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res2.getString("TITLE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res2.getString("JOUR_NAME") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res2.getString("PPD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add2.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd2.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\" id=\"3\" style=\"width:65%; max-height:800px; float:left; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Details of CEP/ Conference/ Lectures attended during the month</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<table class=\"tab\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"4%\">Sr. No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>From Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>To Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Title</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res3!=null && res3.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res3.getString("FMD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res3.getString("TOD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res3.getString("TITLE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add3.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd3.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\" id=\"4\" style=\"width:65%; max-height:800px; float:left; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Details of TC/ any presentations you have made last</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<table class=\"tab\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"6%\">Sr. No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"40%\">Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Title</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res4!=null && res4.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res4.getString("TCD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res4.getString("TITLE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add4.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd4.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\" id=\"5\" style=\"width:65%; max-height:800px; float:left; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Details of TDs during the month</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<table class=\"tab\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"4%\">Sr. No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>From Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>To Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Place</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Purpose of visit</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res5!=null && res5.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res5.getString("FMD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res5.getString("TOD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res5.getString("PLACE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res5.getString("PURPOSE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add5.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd5.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"card\" id=\"6\" style=\"width:65%; max-height:800px; float:left; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Details of leave taken during the month</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<table class=\"tab\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"4%\">Sr. No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>From Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>To Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Nature of leave</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res6!=null && res6.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res6.getString("FMD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res6.getString("TOD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res6.getString("LEAVE_TYPE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add6.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd6.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"card\" id=\"7\" style=\"width:65%; max-height:800px; float:left; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Visits to Fabrication agencies during the month</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<table class=\"tab\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"4%\">Sr. No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Industry</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Visit Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Purpose/ Outcome</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res7!=null && res7.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res7.getString("INDUSTRY") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res7.getString("VISD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res7.getString("PURPOSE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add7.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd7.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"card\" id=\"8\" style=\"width:65%; max-height:800px; float:left; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Details of meetings attended during the month</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<table class=\"tab\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"4%\">Sr. No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Project/ Place Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Purpose/ Outcome</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res8!=null && res8.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res8.getString("PROJECT_NAME") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res8.getString("MD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res8.getString("PURPOSE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add8.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd8.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"card\" id=\"9\" style=\"width:65%; max-height:800px; float:left; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Details of work in Progress</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<table class=\"tab\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"4%\">Sr. No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Project</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Description</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>PDC</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res9!=null && res9.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res9.getString("PROJECT_NAME") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res9.getString("DESCRIPTION") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res9.getString("STATUS") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res9.getString("PCD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add9.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd9.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"card\" id=\"10\" style=\"width:70%; overflow:auto; max-height:800px; float:left; display:none;\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>Other Details</legend>\r\n");
      out.write("\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t<b>Details of DWGs generated during the month</b><br><br>\r\n");
      out.write("\t\t\t\t<table class=\"tab\">\r\n");
      out.write("\t\t\t\t\t<tr style=\"display: none;\"></tr>\r\n");
      out.write("\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("DRAWING_DETAILS")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"8%\">");
      out.print(i );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
i++; 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<b>Details of administrative work done during the month</b><br><br>\r\n");
      out.write("\t\t\t\t<table class=\"tab\">\r\n");
      out.write("\t\t\t\t\t<tr style=\"display: none;\"></tr>\r\n");
      out.write("\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("WORK_DETAILS")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"8%\">");
      out.print(i );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
i++; 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<b>Details of research work done on the topic assigned to you</b><br><br>\r\n");
      out.write("\t\t\t\t<table class=\"tab\">\r\n");
      out.write("\t\t\t\t\t<tr style=\"display: none;\"></tr>\r\n");
      out.write("\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("RESEARCH")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"8%\">");
      out.print(i );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
i++; 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<b>Details of internal technical work review</b><br><br>\r\n");
      out.write("\t\t\t\t<table class=\"tab\">\r\n");
      out.write("\t\t\t\t\t<tr style=\"display: none;\"></tr>\r\n");
      out.write("\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("INT_TECH")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"8%\">");
      out.print(i );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
i++; 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<b>Details of technical work done during the month</b><br><br>\r\n");
      out.write("\t\t\t\t<table class=\"tab\">\r\n");
      out.write("\t\t\t\t\t<tr style=\"display: none;\"></tr>\r\n");
      out.write("\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("TECH_DETAILS")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"8%\">");
      out.print(i );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
i++; 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"tabDiv\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<b>Details of any input awaited from project</b><br><br>\r\n");
      out.write("\t\t\t\t<table class=\"tab\">\r\n");
      out.write("\t\t\t\t\t<tr style=\"display: none;\"></tr>\r\n");
      out.write("\t\t\t\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("INPUT_PROJECT")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"8%\">");
      out.print(i );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"2%\">:</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
i++; 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"noData\"></div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"add10.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Add\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"upd10.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"logout\">\r\n");
      out.write("<form action=\"login.jsp\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"logout\" name=\"logout\"/>\r\n");
      out.write("\t<input type=\"submit\" value=\"Logout\"></input>\r\n");
      out.write("</form>\r\n");
      out.write("<br>\r\n");
      out.write("<form action=\"reportGen.jsp\" method=\"post\" target=\"_blank\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"user\" name=\"reportType\"/>\r\n");
      out.write("\t<input type=\"submit\" value=\"View Report\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"snackbar\">Added Successfully</div>\r\n");
      out.write("<div id=\"snackbar1\">Updated Successfully</div>\r\n");
      out.write("\r\n");
if(s.getAttribute("add")!=null){ 
      out.write("\r\n");
      out.write("<div id=\"toast\" style=\"display:none;\"></div>\r\n");
s.setAttribute("add",null);} 
      out.write('\r');
      out.write('\n');
if(s.getAttribute("update")!=null){
      out.write("\r\n");
      out.write("<div id=\"toast1\" style=\"display:none;\"></div>\r\n");
s.setAttribute("update",null);}
      out.write('\r');
      out.write('\n');
 dbConnection.close(); 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
