/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-04-01 20:43:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BasicServlet.*;
import java.sql.*;

public final class index3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\t\tbackground:#eddeff\r\n");
      out.write("\t\t}\r\n");
      out.write("input[type=submit]{\r\n");
      out.write("\t\t\tbackground-color: #555555;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\theight:40px;\r\n");
      out.write("\t\t\tborder:none;\r\n");
      out.write("\t\t\tcolor:whitesmoke;\r\n");
      out.write("\t\t\tfont-size: medium;\r\n");
      out.write("\t\t\t/* padding: 15px; */\r\n");
      out.write("\t\t\tbox-shadow: 0 0 7px 0 #000;\r\n");
      out.write("\t\t\t/* padding-bottom: 20px; */\r\n");
      out.write("\t\t\tpadding-left: 15px;\r\n");
      out.write("\t\t\tpadding-right: 15px;\r\n");
      out.write("\t\t\tmargin: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.div-table-row input[type=submit]{\r\n");
      out.write("\t\t\tbackground-color: #555555;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t\tborder:none;\r\n");
      out.write("\t\t\tcolor:whitesmoke;\r\n");
      out.write("\t\t\tfont-size: medium;\r\n");
      out.write("\t\t\t/* padding: 15px; */\r\n");
      out.write("\t\t\tbox-shadow: 0 0 7px 0 #000;\r\n");
      out.write("\t\t\t/* padding-bottom: 20px; */\r\n");
      out.write("\t\t\tpadding-left: 15px;\r\n");
      out.write("\t\t\tpadding-right: 15px;\r\n");
      out.write("\t\t\tmargin: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tinput[type=button]{\r\n");
      out.write("\t\t\tbackground-color: #555555;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t\tborder:none;\r\n");
      out.write("\t\t\tcolor:whitesmoke;\r\n");
      out.write("\t\t\tfont-size: medium;\r\n");
      out.write("\t\t\t/* padding: 15px; */\r\n");
      out.write("\t\t\tbox-shadow: 0 0 7px 0 #000;\r\n");
      out.write("\t\t\t/* padding-bottom: 20px; */\r\n");
      out.write("\t\t\tpadding-left: 15px;\r\n");
      out.write("\t\t\tpadding-right: 15px;\r\n");
      out.write("\t\t\tmargin: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.card {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\theight: auto;\r\n");
      out.write("\t\t\tpadding: 40px 30px;\r\n");
      out.write("\t\t\tbox-shadow: 0 0 10px 0 #000;\r\n");
      out.write("\t\t\t/* position: relative; */\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\tmargin: 15px 15px;\r\n");
      out.write("\t\t}\r\n");
      out.write(".div-table {\r\n");
      out.write("  display: table;    \r\n");
      out.write("  margin: auto; \r\n");
      out.write("  margin-left: 1%;           \r\n");
      out.write("font-size: large;\r\n");
      out.write("\tmax-height: 250px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\toverflow-y: auto;\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".div-table-row {\r\n");
      out.write("  display: table-row;\r\n");
      out.write("  clear: both;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  font-size: large;\r\n");
      out.write("}\r\n");
      out.write(".div-table-col {\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-size: large;\r\n");
      out.write("border: 0.5px solid rgb(139, 137, 137);  float: left;\r\n");
      out.write("  display: table-column;\r\n");
      out.write("  height:40px;   \r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  align-items: center;  \r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  align-content: center;\r\n");
      out.write("  flex-direction: column; \r\n");
      out.write("}\r\n");
      out.write(".div-table-col-head{\r\n");
      out.write("\theight: 55px;\r\n");
      out.write("\tborder: 0.5px solid rgb(139, 137, 137);\r\n");
      out.write("  background: #36304a;\r\n");
      out.write("  color: whitesmoke;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  float: left;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("  display: table-column; \r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  align-content: center;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("input[type=text]{\r\n");
      out.write("\tfont-size: large;\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("}\r\n");
      out.write("p{\r\n");
      out.write("\tfont-size:20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#snackbar,#snackbar1 {\r\n");
      out.write("  visibility: hidden;\r\n");
      out.write("  min-width: 250px;\r\n");
      out.write("  float:right;\r\n");
      out.write("  background-color: rgb(75, 74, 74);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  right:5%;\r\n");
      out.write("  bottom: 30px;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#snackbar.show,#snackbar1.show {\r\n");
      out.write("  visibility: visible;\r\n");
      out.write("  -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;\r\n");
      out.write("  animation: fadein 0.5s, fadeout 0.5s 2.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes fadein {\r\n");
      out.write("  from {bottom: 0; opacity: 0;} \r\n");
      out.write("  to {bottom: 30px; opacity: 1;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes fadein {\r\n");
      out.write("  from {bottom: 0; opacity: 0;}\r\n");
      out.write("  to {bottom: 30px; opacity: 1;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes fadeout {\r\n");
      out.write("  from {bottom: 30px; opacity: 1;} \r\n");
      out.write("  to {bottom: 0; opacity: 0;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes fadeout {\r\n");
      out.write("  from {bottom: 30px; opacity: 1;}\r\n");
      out.write("  to {bottom: 0; opacity: 0;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"myFunction()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");

HttpSession s= request.getSession(true);
Employee emp=(Employee) s.getAttribute("emp");
DBConnect db=(DBConnect)s.getAttribute("db");
String month=request.getParameter("start");
if(month==null){
	month=(String) s.getAttribute("month");
}
ResultSet res=null;
if(month==null){
	System.out.println("hi");
}
else{
System.out.println(month);
s.setAttribute("month", month);
res=db.DisplayData(month,emp.persno);
}
int i=1;
s.setAttribute("update",1);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction myFunction() {\r\n");
      out.write("\t\tif(document.getElementById(\"toast\")!=null){\r\n");
      out.write("\t\t\tvar x = document.getElementById(\"snackbar\");\r\n");
      out.write("\t\t\t  x.className = \"show\";\r\n");
      out.write("\t\t\t  setTimeout(function(){ x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t  if(document.getElementById(\"toast1\")!=null){\r\n");
      out.write("\t\t\tvar x = document.getElementById(\"snackbar1\");\r\n");
      out.write("\t\t\t  x.className = \"show\";\r\n");
      out.write("\t\t\t  setTimeout(function(){ x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("function update(i){\r\n");
      out.write("\tdocument.getElementById('upd'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('sub'+i).style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById('pnameL'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('pnameI'+i).style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById('descL'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('descI'+i).style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById('stsL'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('stsI'+i).style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById('pdcL'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('pdcI'+i).style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"card\" style=\"width:25%;margin-left:3.5%;\">\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<legend style=\"font-weight: bold;font-size: large;\">Select Month</legend>\r\n");
      out.write("\t\t<div style=\"text-align: center;align-items: center;\">\r\n");
      out.write("<form action=\"index3.jsp\" method=\"post\">\r\n");
      out.write("<input type=\"month\" id=\"start\" name=\"start\" required style=\"margin-right: 30px;height: 40px;\" value=");
      out.print(month );
      out.write(">\r\n");
      out.write("<input type=\"submit\" value=\"Next\"/>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"card\" style=\"width:90%;margin:auto;\">\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<legend style=\"font-weight: bold;font-size: large;\">Work in Progress</legend>\r\n");
      out.write("<div class=\"div-table\" id=\"dataTable\">\r\n");
      out.write("\t\t\t<div class=\"div-table-row\">\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:5%\">Sr. No.</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:12%\">Project ID</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:12%\">Project Name</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:18%\">Project Description</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:9%\">WP Date</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:10%\">Status</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:12%\">PDC</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:9.5%\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col-head\" style=\"width:9.5%\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
while(res!=null && res.next()){ 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"div-table-row\">\r\n");
      out.write("\t\t\t<form action=\"UpdateServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:5%\">");
      out.print(i );
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\"  style=\"width:12%\">");
      out.print(res.getString("project_Id") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\"  value=");
      out.print(res.getString("project_Id") );
      out.write(" name=\"projectId\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:12%\">\r\n");
      out.write("\t\t\t\t\t<p id=\"pnameL");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(res.getString("project_Name") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"pnameI");
      out.print(i );
      out.write("\" style=\"display: none;\"value=");
      out.print(res.getString("project_Name") );
      out.write(" name=\"projectName\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:18%\">\r\n");
      out.write("\t\t\t\t\t<p id=\"descL");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(res.getString("Description") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"descI");
      out.print(i );
      out.write("\" style=\"display: none;\"value=");
      out.print(res.getString("Description") );
      out.write(" name=\"projectDesc\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:9%\">");
      out.print(res.getString("wpd") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\"  value=");
      out.print(res.getString("wpd") );
      out.write(" name=\"wpd\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:10%\">\r\n");
      out.write("\t\t\t\t\t<p id=\"stsL");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(res.getString("status") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"stsI");
      out.print(i );
      out.write("\" style=\"display: none;\" value=");
      out.print(res.getString("status") );
      out.write(" name=\"status\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:12%\">\r\n");
      out.write("\t\t\t\t\t<p id=\"pdcL");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(res.getString("PDC") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" id=\"pdcI");
      out.print(i );
      out.write("\" style=\"display: none;\"value=");
      out.print(res.getString("PDC") );
      out.write(" name=\"PDC\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:9.5%\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" onclick=\"update('");
      out.print(i );
      out.write("')\" id=\"upd");
      out.print(i );
      out.write("\" value=\"Update\"/>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" style=\"display: none;\" id=\"sub");
      out.print(i );
      out.write("\" value=\"Save\"/></div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"DeleteServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:9.5%\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(res.getString("project_Id") );
      out.write("\" name=\"projectId\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(res.getString("wpd") );
      out.write("\" name=\"wpd\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(emp.persno );
      out.write("\" name=\"persno\"/>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Delete\"></div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
i++; 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form action=\"home.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Save\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"snackbar\">Updated Successfully</div>\r\n");
      out.write("\t\t<div id=\"snackbar1\">Deleted Successfully</div>\r\n");
      out.write("\t\t");
if(s.getAttribute("upd")!=null){ 
      out.write("\r\n");
      out.write("\t\t\t<div id=\"toast\" style=\"display:none;\"></div>\r\n");
      out.write("\t\t\t");
s.setAttribute("upd",null);} 
      out.write("\r\n");
      out.write("\t\t\t");
if(s.getAttribute("del")!=null){
      out.write("\r\n");
      out.write("\t\t\t<div id=\"toast1\" style=\"display:none;\"></div>\r\n");
      out.write("\t\t\t");
s.setAttribute("del",null);}
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
