/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-03-29 18:26:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BasicServlet.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

HttpSession s= request.getSession(true);
Employee emp=(Employee) s.getAttribute("emp");
DBConnect db=(DBConnect)s.getAttribute("db");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction addRow(tableID) {  \r\n");
      out.write("        var table = document.getElementById(tableID);  \r\n");
      out.write("        var rowCount = table.rows.length;  \r\n");
      out.write("        var row = table.insertRow(rowCount);\r\n");
      out.write("        \r\n");
      out.write("        var cell0 = row.insertCell(0);\r\n");
      out.write("        var cell1 = row.insertCell(1);\r\n");
      out.write("        var cell2 = row.insertCell(2);\r\n");
      out.write("        var cell3 = row.insertCell(3);\r\n");
      out.write("        var cell4 = row.insertCell(4);\r\n");
      out.write("        var cell5 = row.insertCell(5);\r\n");
      out.write("        var cell6 = row.insertCell(6);\r\n");
      out.write("        var cell7 = row.insertCell(7);\r\n");
      out.write("        cell0.innerHTML = rowCount; \r\n");
      out.write("        \r\n");
      out.write("        var element1 = document.createElement(\"input\");\r\n");
      out.write("        element1.type = \"text\";\r\n");
      out.write("        element1.setAttribute('value', '');\r\n");
      out.write("        element1.setAttribute('name', 'projectId'+rowCount);\r\n");
      out.write("        cell1.appendChild(element1);\r\n");
      out.write("        \r\n");
      out.write("        var element2 = document.createElement(\"input\");\r\n");
      out.write("        element2.type = \"text\";\r\n");
      out.write("        element2.setAttribute('value', '');\r\n");
      out.write("        element2.setAttribute('name', 'projectName'+rowCount);\r\n");
      out.write("        cell2.appendChild(element2);\r\n");
      out.write("        \r\n");
      out.write("        var element3 = document.createElement(\"input\");\r\n");
      out.write("        element3.type = \"text\";\r\n");
      out.write("        element3.setAttribute('value', '');\r\n");
      out.write("        element3.setAttribute('name', 'projectDesc'+rowCount);\r\n");
      out.write("        cell3.appendChild(element3);\r\n");
      out.write("        \r\n");
      out.write("        var element4 = document.createElement(\"input\");\r\n");
      out.write("        element4.type = \"date\";\r\n");
      out.write("        element4.setAttribute('name', 'WPDate'+rowCount);\r\n");
      out.write("        cell4.appendChild(element4);\r\n");
      out.write("        \r\n");
      out.write("        var element5 = document.createElement(\"input\");\r\n");
      out.write("        element5.type = \"text\";\r\n");
      out.write("        element5.setAttribute('value', '');\r\n");
      out.write("        element5.setAttribute('name', 'status'+rowCount);\r\n");
      out.write("        cell5.appendChild(element5);\r\n");
      out.write("        \r\n");
      out.write("        var element6 = document.createElement(\"input\");\r\n");
      out.write("        element6.type = \"date\";\r\n");
      out.write("        element6.setAttribute('name', 'PDC'+rowCount);\r\n");
      out.write("        cell6.appendChild(element6);\r\n");
      out.write("        \r\n");
      out.write("        var element7 = document.createElement(\"input\");  \r\n");
      out.write("        element7.type = \"button\";\r\n");
      out.write("        element7.name = \"button\"+rowCount;\r\n");
      out.write("        element7.setAttribute('value', 'Delete');\r\n");
      out.write("        element7.onclick = function () { removeRow(\"button\"+rowCount); }\r\n");
      out.write("        cell7.appendChild(element7);\r\n");
      out.write("    }\r\n");
      out.write("    function removeRow(btnName) {  \r\n");
      out.write("        try {\r\n");
      out.write("            var table = document.getElementById('dataTable');  \r\n");
      out.write("            var rowCount = table.rows.length;\r\n");
      out.write("            for(var i = 1; i < rowCount; i++){\r\n");
      out.write("                var row = table.rows[i];\r\n");
      out.write("                var rowObj = row.cells[7].childNodes[0];\r\n");
      out.write("                if (rowObj.name == btnName) {\r\n");
      out.write("                    table.deleteRow(i);\r\n");
      out.write("                    for(var j=i;j<rowCount-1;j++){\r\n");
      out.write("              \t\t\ttable.rows[j].cells[0].innerHTML=j;\r\n");
      out.write("              \t\t}\r\n");
      out.write("                    break;\r\n");
      out.write("                }  \r\n");
      out.write("            }  \r\n");
      out.write("        }  \r\n");
      out.write("        catch (e) {  \r\n");
      out.write("            alert(e);\r\n");
      out.write("        }  \r\n");
      out.write("    }  \r\n");
      out.write("</SCRIPT> \r\n");
      out.write("<h2>Modify Work in Progress</h2>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\t<form action=\"SaveServlet\" method=\"post\">\r\n");
      out.write("\t\t<TABLE id=\"dataTable\" border=\"1\">\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TH>Sr.<br> No.</TH>\r\n");
      out.write("\t\t\t\t<TH>Project ID</TH>\r\n");
      out.write("\t\t\t\t<TH>Project Name</TH>\r\n");
      out.write("\t\t\t\t<TH>Project Description</TH>\r\n");
      out.write("\t\t\t\t<TH>WP Date</TH>\r\n");
      out.write("\t\t\t\t<TH>Status</TH>\r\n");
      out.write("\t\t\t\t<TH>PDC</TH>\r\n");
      out.write("\t\t\t\t<TH></TH>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD>1</TD>\r\n");
      out.write("\t\t\t\t<TD><input type=\"text\" value=\"\" name=\"projectId1\"></TD>\r\n");
      out.write("\t\t\t\t<TD><input type=\"text\" value=\"\" name=\"projectName1\"></TD>\r\n");
      out.write("\t\t\t\t<TD><input type=\"text\" value=\"\" name=\"projectDesc1\"></TD>\r\n");
      out.write("\t\t\t\t<TD><input type=\"date\" value=\"\" name=\"WPDate1\"></TD>\r\n");
      out.write("\t\t\t\t<TD><input type=\"text\" value=\"\" name=\"status1\"></TD>\r\n");
      out.write("\t\t\t\t<TD><input type=\"date\" value=\"\" name=\"PDC1\"></TD>\r\n");
      out.write("\t\t\t\t<TD><input type=\"button\" name=\"button1\" value=\"Delete\" onclick=\"removeRow('button1')\"></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t</TABLE>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"save\"/>\r\n");
      out.write("\t\t<INPUT type=\"button\" value=\"Add Row\" onclick=\"addRow('dataTable')\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
