/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-03-29 19:13:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BasicServlet.*;
import java.sql.*;

public final class index3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".div-table {\r\n");
      out.write("  display: table;         \r\n");
      out.write("  width: auto;                 \r\n");
      out.write("  border: 2px solid #666666;\r\n");
      out.write("}\r\n");
      out.write(".div-table-row {\r\n");
      out.write("  display: table-row;\r\n");
      out.write("  width: auto;\r\n");
      out.write("  clear: both;\r\n");
      out.write("}\r\n");
      out.write(".div-table-col {\r\n");
      out.write("margin: 2px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("border:2px solid #666666;\r\n");
      out.write("  float: left;\r\n");
      out.write("  display: table-column;         \r\n");
      out.write("  width: 200px;\r\n");
      out.write("  height:30px;          \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

HttpSession s= request.getSession(true);
Employee emp=(Employee) s.getAttribute("emp");
DBConnect db=(DBConnect)s.getAttribute("db");
String month=request.getParameter("start");
if(month==null){
	month=(String) s.getAttribute("month");
}
s.setAttribute("month", month);
ResultSet res=db.DisplayData(month,emp.persno);
if(res==null){
	RequestDispatcher rd=request.getRequestDispatcher("index1.jsp");
	rd.forward(request, response);
}
int i=1;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function update(i){\r\n");
      out.write("\tdocument.getElementById('upd'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('sub'+i).style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById('pnameL'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('pnameI'+i).style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById('descL'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('descI'+i).style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById('stsL'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('stsI'+i).style.display=\"block\";\r\n");
      out.write("\tdocument.getElementById('pdcL'+i).style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('pdcI'+i).style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<h2>Modify Work in Progress</h2>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"div-table\" id=\"dataTable\">\r\n");
      out.write("\t\t\t<div class=\"div-table-row\">\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:60px\">Sr. No.</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">Project ID</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">Project Name</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">Project Description</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">WP Date</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">Status</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">PDC</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:60px\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:60px\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
while(res!=null && res.next()){ 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"div-table-row\">\r\n");
      out.write("\t\t\t<form action=\"UpdateServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:60px\">");
      out.print(i );
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">");
      out.print(res.getString("project_Id") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\"  value=");
      out.print(res.getString("project_Id") );
      out.write(" name=\"projectId\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">\r\n");
      out.write("\t\t\t\t\t<p id=\"pnameL");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(res.getString("project_Name") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"pnameI");
      out.print(i );
      out.write("\" style=\"display: none;\"value=");
      out.print(res.getString("project_Name") );
      out.write(" name=\"projectName\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">\r\n");
      out.write("\t\t\t\t\t<p id=\"descL");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(res.getString("Description") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"descI");
      out.print(i );
      out.write("\" style=\"display: none;\"value=");
      out.print(res.getString("Description") );
      out.write(" name=\"projectDesc\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">");
      out.print(res.getString("wpd") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\"  value=");
      out.print(res.getString("wpd") );
      out.write(" name=\"wpd\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">\r\n");
      out.write("\t\t\t\t\t<p id=\"stsL");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(res.getString("status") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"stsI");
      out.print(i );
      out.write("\" style=\"display: none;\" value=");
      out.print(res.getString("status") );
      out.write(" name=\"status\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\">\r\n");
      out.write("\t\t\t\t\t<p id=\"pdcL");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(res.getString("PDC") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" id=\"pdcI");
      out.print(i );
      out.write("\" style=\"display: none;\"value=");
      out.print(res.getString("PDC") );
      out.write(" name=\"PDC\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:60px\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" onclick=\"update('");
      out.print(i );
      out.write("')\" id=\"upd");
      out.print(i );
      out.write("\" value=\"Update\"/>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" style=\"display: none;\" id=\"sub");
      out.print(i );
      out.write("\" value=\"Save\"/></div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"DeleteServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"div-table-col\" style=\"width:60px\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(res.getString("project_Id") );
      out.write("\" name=\"projectId\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(res.getString("wpd") );
      out.write("\" name=\"wpd\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(emp.persno );
      out.write("\" name=\"persno\"/>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Delete\"></div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
i++; 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form action=\"index1.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"save\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
