/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-04-15 15:31:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");

HttpSession s= request.getSession(true);
 
      out.write("\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<title>Login</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tbody{\r\n");
      out.write("\t\t\tbackground: #eddeff\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.login {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\twidth: 30%;\r\n");
      out.write("\t\t\theight: auto;\r\n");
      out.write("\t\t\tpadding: 40px 30px;\r\n");
      out.write("\t\t\tbox-shadow: 0 0 10px 0 #000;\r\n");
      out.write("\t\t\tmargin: auto;\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tinput {\r\n");
      out.write("\t\t\twidth: 100%;\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t\tborder: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tinput:focus {\r\n");
      out.write("\t\t\tborder: none;\r\n");
      out.write("\t\t\toutline: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tinput[type=submit]{\r\n");
      out.write("\t\t\tbackground-color: #555555;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\theight:40px;\r\n");
      out.write("\t\t\tborder:1px solid #4d4c4c;\r\n");
      out.write("\t\t\tcolor:whitesmoke;\r\n");
      out.write("\t\t\tfont-size: medium;\r\n");
      out.write("\t\t\t/* padding: 15px; */\r\n");
      out.write("\t\t\tbox-shadow: 0 0 7px 0 #000;\r\n");
      out.write("\t\t\t/* padding-bottom: 20px; */\r\n");
      out.write("\t\t\tpadding-left: 15px;\r\n");
      out.write("\t\t\tpadding-right: 15px;\r\n");
      out.write("\t\t\tmargin: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfieldset {\r\n");
      out.write("\t\t\tmargin-bottom: 15px;\r\n");
      out.write("\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#snackbar,#snackbar1,#snackbar2 {\r\n");
      out.write("  visibility: hidden;\r\n");
      out.write("  min-width: 250px;\r\n");
      out.write("  float:right;\r\n");
      out.write("  background-color: rgb(75, 74, 74);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  right:5%;\r\n");
      out.write("  bottom: 30px;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#snackbar.show,#snackbar1.show,#snackbar2.show {\r\n");
      out.write("  visibility: visible;\r\n");
      out.write("  -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;\r\n");
      out.write("  animation: fadein 0.5s, fadeout 0.5s 2.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes fadein {\r\n");
      out.write("  from {bottom: 0; opacity: 0;} \r\n");
      out.write("  to {bottom: 30px; opacity: 1;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes fadein {\r\n");
      out.write("  from {bottom: 0; opacity: 0;}\r\n");
      out.write("  to {bottom: 30px; opacity: 1;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes fadeout {\r\n");
      out.write("  from {bottom: 30px; opacity: 1;} \r\n");
      out.write("  to {bottom: 0; opacity: 0;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes fadeout {\r\n");
      out.write("  from {bottom: 30px; opacity: 1;}\r\n");
      out.write("  to {bottom: 0; opacity: 0;}\r\n");
      out.write("}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"myFunction()\">\r\n");
      out.write("<script>\r\n");
      out.write("function myFunction() {\r\n");
      out.write("\tif(document.getElementById(\"toast\")!=null){\r\n");
      out.write("\t\tvar x = document.getElementById(\"snackbar\");\r\n");
      out.write("\t\t  x.className = \"show\";\r\n");
      out.write("\t\t  setTimeout(function(){ x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if(document.getElementById(\"toast1\")!=null){\r\n");
      out.write("\t\tvar x = document.getElementById(\"snackbar1\");\r\n");
      out.write("\t\t  x.className = \"show\";\r\n");
      out.write("\t\t  setTimeout(function(){ x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if(document.getElementById(\"toast2\")!=null){\r\n");
      out.write("\t\tvar x = document.getElementById(\"snackbar2\");\r\n");
      out.write("\t\t  x.className = \"show\";\r\n");
      out.write("\t\t  setTimeout(function(){ x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\t<div class=\"login\">\r\n");
      out.write("\t\t<form action=\"validateLogin.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"list\">\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<h2>Member Login</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>User Id</legend>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"userId\" />\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>Password</legend>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password\" />\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div><input type=\"submit\" value=\"Submit\" /></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"snackbar\">Successfully Logged Out</div>\r\n");
      out.write("\t<div id=\"snackbar1\">Invalid User Id or Password</div>\r\n");
      out.write("\t<div id=\"snackbar2\">Session Timed out or Error</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
if(s.getAttribute("logout")!=null){ 
      out.write("\r\n");
      out.write("\t<div id=\"toast\" style=\"display:none;\"></div>\r\n");
      out.write("\t");
} 
      out.write('\r');
      out.write('\n');
      out.write('	');
if(s.getAttribute("invalid")!=null){
      out.write("\r\n");
      out.write("\t<div id=\"toast1\" style=\"display:none;\"></div>\r\n");
      out.write("\t");
}
      out.write('\r');
      out.write('\n');
      out.write('	');
if(s.getAttribute("timeout")!=null){
      out.write("\r\n");
      out.write("\t<div id=\"toast2\" style=\"display:none;\"></div>\r\n");
      out.write("\t");
}s.invalidate();
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
