/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-08 16:48:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t");
 HttpSession s=request.getSession(true); 
      out.write("\r\n");
      out.write("\t\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t\t<title>Login</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t@import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');\r\n");
      out.write("\r\n");
      out.write("\t\t\t* {\r\n");
      out.write("\t\t\t\tmargin: 0;\r\n");
      out.write("\t\t\t\tpadding: 0;\r\n");
      out.write("\t\t\t\tbox-sizing: border-box;\r\n");
      out.write("\t\t\t\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\thtml,\r\n");
      out.write("\t\t\tbody {\r\n");
      out.write("\t\t\t\tdisplay: grid;\r\n");
      out.write("\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\tplace-items: center;\r\n");
      out.write("\t\t\t\t/* background: -webkit-linear-gradient(left, #a445b2, #fa4299); */\r\n");
      out.write("\t\t\t\tbackground: #eddeff\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t::selection {\r\n");
      out.write("\t\t\t\t/* background: #fa4299; */\r\n");
      out.write("\t\t\t\tbackground: #c99efd;\r\n");
      out.write("\t\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.wrapper {\r\n");
      out.write("\t\t\t\toverflow: hidden;\r\n");
      out.write("\t\t\t\tmax-width: 390px;\r\n");
      out.write("\t\t\t\twidth: 70%;\r\n");
      out.write("\t\t\t\tmin-width: 200px;\r\n");
      out.write("\t\t\t\theight: auto;\r\n");
      out.write("\t\t\t\tbackground: #fff;\r\n");
      out.write("\t\t\t\tpadding: 40px 30px;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t\tbox-shadow: 0 0 10px 0 #000;\r\n");
      out.write("\t\t\t\tmargin: auto;\r\n");
      out.write("\t\t\t\tposition: relative;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.wrapper .title-text {\r\n");
      out.write("\t\t\t\tdisplay: flex;\r\n");
      out.write("\t\t\t\twidth: 200%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.wrapper .title {\r\n");
      out.write("\t\t\t\twidth: 50%;\r\n");
      out.write("\t\t\t\tfont-size: 35px;\r\n");
      out.write("\t\t\t\tfont-weight: 600;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\ttransition: all 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.wrapper .slide-controls {\r\n");
      out.write("\t\t\t\tposition: relative;\r\n");
      out.write("\t\t\t\tdisplay: flex;\r\n");
      out.write("\t\t\t\theight: 50px;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\toverflow: hidden;\r\n");
      out.write("\t\t\t\tmargin: 30px 0 10px 0;\r\n");
      out.write("\t\t\t\tjustify-content: space-between;\r\n");
      out.write("\t\t\t\tborder: 1px solid lightgrey;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.slide-controls .slide {\r\n");
      out.write("\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\t\tfont-size: 18px;\r\n");
      out.write("\t\t\t\tfont-weight: 500;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tline-height: 48px;\r\n");
      out.write("\t\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\t\tz-index: 1;\r\n");
      out.write("\t\t\t\ttransition: all 0.6s ease;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.slide-controls label.director {\r\n");
      out.write("\t\t\t\tcolor: #000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.slide-controls .slider-tab {\r\n");
      out.write("\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\twidth: 50%;\r\n");
      out.write("\t\t\t\tleft: 0;\r\n");
      out.write("\t\t\t\tz-index: 0;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t\tbackground: #a764fa;\r\n");
      out.write("\t\t\t\ttransition: all 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[type=\"radio\"] {\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#director:checked~.slider-tab {\r\n");
      out.write("\t\t\t\tleft: 50%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#director:checked~label.director {\r\n");
      out.write("\t\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\t\tcursor: default;\r\n");
      out.write("\t\t\t\tuser-select: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#director:checked~label.user {\r\n");
      out.write("\t\t\t\tcolor: #000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#user:checked~label.director {\r\n");
      out.write("\t\t\t\tcolor: #000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#user:checked~label.user {\r\n");
      out.write("\t\t\t\tcursor: default;\r\n");
      out.write("\t\t\t\tuser-select: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.wrapper .form-container {\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\toverflow: hidden;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.form-container .form-inner {\r\n");
      out.write("\t\t\t\tdisplay: flex;\r\n");
      out.write("\t\t\t\twidth: 200%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.form-container .form-inner form {\r\n");
      out.write("\t\t\t\twidth: 50%;\r\n");
      out.write("\t\t\t\ttransition: all 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.form-inner form .field {\r\n");
      out.write("\t\t\t\theight: 50px;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\tmargin-top: 20px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.form-inner form .field input {\r\n");
      out.write("\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\toutline: none;\r\n");
      out.write("\t\t\t\tpadding-left: 15px;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t\tborder: 1px solid lightgrey;\r\n");
      out.write("\t\t\t\tborder-bottom-width: 2px;\r\n");
      out.write("\t\t\t\tfont-size: 17px;\r\n");
      out.write("\t\t\t\ttransition: all 0.3s ease;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.form-inner form .field input:focus {\r\n");
      out.write("\t\t\t\tborder-color: #a764fa;\r\n");
      out.write("\t\t\t\t/* box-shadow: inset 0 0 3px #fb6aae; */\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.form-inner form .field input::placeholder {\r\n");
      out.write("\t\t\t\tcolor: #999;\r\n");
      out.write("\t\t\t\ttransition: all 0.3s ease;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tform .field input:focus::placeholder {\r\n");
      out.write("\t\t\t\tcolor: #b3b3b3;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.form-inner form .pass-link {\r\n");
      out.write("\t\t\t\tmargin-top: 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.form-inner form .director-link {\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tmargin-top: 30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tform .btn {\r\n");
      out.write("\t\t\t\theight: 50px;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t\tposition: relative;\r\n");
      out.write("\t\t\t\toverflow: hidden;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tform .btn .btn-layer {\r\n");
      out.write("\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\twidth: 300%;\r\n");
      out.write("\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\tleft: -100%;\r\n");
      out.write("\t\t\t\tbackground: #a764fa;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t\ttransition: all 0.4s ease;\r\n");
      out.write("\t\t\t\t;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tform .btn:hover .btn-layer {\r\n");
      out.write("\t\t\t\tleft: 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tform .btn input[type=\"submit\"] {\r\n");
      out.write("\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\tz-index: 1;\r\n");
      out.write("\t\t\t\tposition: relative;\r\n");
      out.write("\t\t\t\tbackground: none;\r\n");
      out.write("\t\t\t\tborder: none;\r\n");
      out.write("\t\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\t\tpadding-left: 0;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\t\tfont-weight: 500;\r\n");
      out.write("\t\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#snackbar,\r\n");
      out.write("\t\t\t#snackbar1,\r\n");
      out.write("\t\t\t#snackbar2 {\r\n");
      out.write("\t\t\t\tvisibility: hidden;\r\n");
      out.write("\t\t\t\tmin-width: 250px;\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t\t\t\tbackground-color: rgb(75, 74, 74);\r\n");
      out.write("\t\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tborder-radius: 2px;\r\n");
      out.write("\t\t\t\tpadding: 16px;\r\n");
      out.write("\t\t\t\tposition: fixed;\r\n");
      out.write("\t\t\t\tz-index: 1;\r\n");
      out.write("\t\t\t\tright: 5%;\r\n");
      out.write("\t\t\t\tbottom: 30px;\r\n");
      out.write("\t\t\t\tfont-size: 17px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#snackbar.show,\r\n");
      out.write("\t\t\t#snackbar1.show,\r\n");
      out.write("\t\t\t#snackbar2.show {\r\n");
      out.write("\t\t\t\tvisibility: visible;\r\n");
      out.write("\t\t\t\t-webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;\r\n");
      out.write("\t\t\t\tanimation: fadein 0.5s, fadeout 0.5s 2.5s;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t@-webkit-keyframes fadein {\r\n");
      out.write("\t\t\t\tfrom {\r\n");
      out.write("\t\t\t\t\tbottom: 0;\r\n");
      out.write("\t\t\t\t\topacity: 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tto {\r\n");
      out.write("\t\t\t\t\tbottom: 30px;\r\n");
      out.write("\t\t\t\t\topacity: 1;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t@keyframes fadein {\r\n");
      out.write("\t\t\t\tfrom {\r\n");
      out.write("\t\t\t\t\tbottom: 0;\r\n");
      out.write("\t\t\t\t\topacity: 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tto {\r\n");
      out.write("\t\t\t\t\tbottom: 30px;\r\n");
      out.write("\t\t\t\t\topacity: 1;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t@-webkit-keyframes fadeout {\r\n");
      out.write("\t\t\t\tfrom {\r\n");
      out.write("\t\t\t\t\tbottom: 30px;\r\n");
      out.write("\t\t\t\t\topacity: 1;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tto {\r\n");
      out.write("\t\t\t\t\tbottom: 0;\r\n");
      out.write("\t\t\t\t\topacity: 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t@keyframes fadeout {\r\n");
      out.write("\t\t\t\tfrom {\r\n");
      out.write("\t\t\t\t\tbottom: 30px;\r\n");
      out.write("\t\t\t\t\topacity: 1;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tto {\r\n");
      out.write("\t\t\t\t\tbottom: 0;\r\n");
      out.write("\t\t\t\t\topacity: 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body onload=\"myFunction()\">\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tfunction myFunction() {\r\n");
      out.write("\t\t\t\tif (document.getElementById(\"toast\") != null) {\r\n");
      out.write("\t\t\t\t\tvar x = document.getElementById(\"snackbar\");\r\n");
      out.write("\t\t\t\t\tx.className = \"show\";\r\n");
      out.write("\t\t\t\t\tsetTimeout(function () { x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (document.getElementById(\"toast1\") != null) {\r\n");
      out.write("\t\t\t\t\tvar x = document.getElementById(\"snackbar1\");\r\n");
      out.write("\t\t\t\t\tx.className = \"show\";\r\n");
      out.write("\t\t\t\t\tsetTimeout(function () { x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (document.getElementById(\"toast2\") != null) {\r\n");
      out.write("\t\t\t\t\tvar x = document.getElementById(\"snackbar2\");\r\n");
      out.write("\t\t\t\t\tx.className = \"show\";\r\n");
      out.write("\t\t\t\t\tsetTimeout(function () { x.className = x.className.replace(\"show\", \"\"); }, 3000);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t<div class=\"title-text\">\r\n");
      out.write("\t\t\t\t<div class=\"title user\">\r\n");
      out.write("\t\t\t\t\tUser Login</div>\r\n");
      out.write("\t\t\t\t<div class=\"title director\">\r\n");
      out.write("\t\t\t\t\tDirector Login</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-container\">\r\n");
      out.write("\t\t\t\t<div class=\"slide-controls\">\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"slide\" id=\"user\" checked>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"slide\" id=\"director\">\r\n");
      out.write("\t\t\t\t\t<label for=\"user\" class=\"slide user\">User</label>\r\n");
      out.write("\t\t\t\t\t<label for=\"director\" class=\"slide director\">Director</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-tab\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-inner\">\r\n");
      out.write("\t\t\t\t\t<form action=\"validateLogin.jsp\" method=\"post\" class=\"user\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" required placeholder=\"User Id\" name=\"userId\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"Password\" name=\"password\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"btn-layer\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"user\" name=\"loginType\"/>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form action=\"validateLogin.jsp\" method=\"post\" class=\"director\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" required placeholder=\"User Id\" name=\"userId\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"Password\" name=\"password\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"field btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"btn-layer\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"director\" name=\"loginType\"/>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tconst userText = document.querySelector(\".title-text .user\");\r\n");
      out.write("\t\t\tconst userForm = document.querySelector(\"form.user\");\r\n");
      out.write("\t\t\tconst userBtn = document.querySelector(\"label.user\");\r\n");
      out.write("\t\t\tconst directorBtn = document.querySelector(\"label.director\");\r\n");
      out.write("\t\t\tdirectorBtn.onclick = (() => {\r\n");
      out.write("\t\t\t\tuserForm.style.marginLeft = \"-50%\";\r\n");
      out.write("\t\t\t\tuserText.style.marginLeft = \"-50%\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tuserBtn.onclick = (() => {\r\n");
      out.write("\t\t\t\tuserForm.style.marginLeft = \"0%\";\r\n");
      out.write("\t\t\t\tuserText.style.marginLeft = \"0%\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"snackbar\">Successfully Logged Out</div>\r\n");
      out.write("\t\t<div id=\"snackbar1\">Invalid User Id or Password</div>\r\n");
      out.write("\t\t<div id=\"snackbar2\">Session Timed out or Error</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");
if(request.getParameter("logout")!=null){ 
      out.write("\r\n");
      out.write("\t\t\t<div id=\"toast\" style=\"display:none;\"></div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t");
if(s.getAttribute("invalid")!=null){
      out.write("\r\n");
      out.write("\t\t\t<div id=\"toast1\" style=\"display:none;\"></div>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t\t");
if(s.getAttribute("timeout")!=null){
      out.write("\r\n");
      out.write("\t\t\t<div id=\"toast2\" style=\"display:none;\"></div>\r\n");
      out.write("\t\t");
}s.invalidate();
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
