/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-09 15:39:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BasicServlet.*;
import java.sql.*;
import java.text.SimpleDateFormat;

public final class reportGen_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Monthly Progress Report</title>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("margin-bottom:10px;\r\n");
      out.write("margin-left:20px;\r\n");
      out.write("margin-top:10px;}\r\n");
      out.write(".header{\r\n");
      out.write("text-align:center;\r\n");
      out.write("align-items:center;\r\n");
      out.write("}\r\n");
      out.write("b{\r\n");
      out.write("margin-bottom:10px;\r\n");
      out.write("font-size:21px;\r\n");
      out.write("}\r\n");
      out.write("#print{\r\n");
      out.write("float:right;\r\n");
      out.write("margin:auto;\r\n");
      out.write("margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("width:90%;\r\n");
      out.write("margin-left:25px;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("border: 1px black solid;\r\n");
      out.write("border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("span{\r\n");
      out.write("font-size:20px;}\r\n");
      out.write("th,td{\r\n");
      out.write("font-size:20px;\r\n");
      out.write("border: 1px black solid;\r\n");
      out.write("border-collapse: collapse;\r\n");
      out.write("height:25px;\r\n");
      out.write("padding:10px;\r\n");
      out.write("}\r\n");
      out.write(".dim{\r\n");
      out.write("color:lightgrey;\r\n");
      out.write("}\r\n");
      out.write(".textBox{\r\n");
      out.write("width:90%;\r\n");
      out.write("margin-left:25px;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("border: 1px black solid;\r\n");
      out.write("min-height:25px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

HttpSession s= request.getSession(true);
Employee emp=(Employee) s.getAttribute("emp");
String period=(String)request.getParameter("month");
String strPeriod=period;
String empName, empPersno;
if(request.getParameter("reportType")!=null){
	if(request.getParameter("reportType").equals("director")){
		empName=(String)request.getParameter("empName");
		empPersno=(String)request.getParameter("persNo");
	}
	else{
		empName=emp.name;
		empPersno=emp.persno;
	}
	s.setAttribute("empName",empName);
	s.setAttribute("persNo",empPersno);
}
else{
	empName=(String)s.getAttribute("empName");
	empPersno=(String)s.getAttribute("persNo");
}
if(period!=null && !period.equals("")){
	s.setAttribute("period",period);
	//System.out.println(period+"hi");
	SimpleDateFormat formatter=new SimpleDateFormat("yyyy-MM");
	java.util.Date date=formatter.parse(period); 
	SimpleDateFormat formatter1=new SimpleDateFormat("MMMM, yyyy");  
	 strPeriod=formatter1.format(date);
}
else{
	period=(String)s.getAttribute("period");
}
if(strPeriod==null || strPeriod==""){
	strPeriod="Select";
}
DNET DNet=new DNET();
Connection dbConnection=DNet.getSurveyThinConnection();
PreparedStatement pStatement;

ResultSet res1=null;
try{
	pStatement=dbConnection.prepareStatement("SELECT REP_NO, TO_CHAR(REP_DATE, 'dd/mm/yyyy') as REPD, TITLE FROM "+DNet.MPR_Reports+" WHERE F_CPERSNO=? AND TO_CHAR(REP_DATE,'YYYY-MM') LIKE ? ORDER BY REP_DATE");
	pStatement.setString(1, empPersno); 
	pStatement.setString(2, period);
	res1=pStatement.executeQuery();
} catch (SQLException e){
	e.printStackTrace();
}

ResultSet res2=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TITLE, JOUR_NAME, TO_CHAR(PAPER_DATE, 'dd/mm/yyyy') AS PPD FROM "+DNet.MPR_Papers+" WHERE F_CPERSNO=? AND TO_CHAR(PAPER_DATE,'YYYY-MM') LIKE ? ORDER BY PAPER_DATE");
	pStatement.setString(1, empPersno);  
	pStatement.setString(2, period);
	res2=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res3=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TO_CHAR(FROM_DATE, 'dd/mm/yyyy') AS FMD, TO_CHAR(TO_DATE, 'dd/mm/yyyy') AS TOD, TITLE FROM "+DNet.MPR_Cep+" WHERE F_CPERSNO=? AND TO_CHAR(FROM_DATE,'YYYY-MM') LIKE ? ORDER BY FROM_DATE");
	pStatement.setString(1, empPersno);  
	pStatement.setString(2, period);
	res3=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res4=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TO_CHAR(TC_DATE, 'dd/mm/yyyy') AS TCD, TITLE FROM "+DNet.MPR_TC+" WHERE F_CPERSNO=? AND TO_CHAR(TC_DATE,'YYYY-MM') LIKE ? ORDER BY TC_DATE");
	pStatement.setString(1, empPersno);  
	pStatement.setString(2, period);
	res4=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res5=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TO_CHAR(FROM_DATE, 'dd/mm/yyyy') AS FMD, TO_CHAR(TO_DATE, 'dd/mm/yyyy') AS TOD, PLACE, PURPOSE FROM "+DNet.MPR_TD+" WHERE F_CPERSNO=? AND TO_CHAR(FROM_DATE,'YYYY-MM') LIKE ? ORDER BY FROM_DATE");
	pStatement.setString(1, empPersno);  
	pStatement.setString(2, period);
	res5=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res6=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT TO_CHAR(FROM_DATE, 'dd/mm/yyyy') AS FMD, TO_CHAR(TO_DATE, 'dd/mm/yyyy') AS TOD, LEAVE_TYPE FROM "+DNet.MPR_Leaves+" WHERE F_CPERSNO=? AND TO_CHAR(FROM_DATE,'YYYY-MM') LIKE ? ORDER BY FROM_DATE");
	pStatement.setString(1, empPersno);  
	pStatement.setString(2, period);
	res6=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res7=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT INDUSTRY, TO_CHAR(VISIT_DATE, 'dd/mm/yyyy') as VISD, PURPOSE FROM "+DNet.MPR_FabricationVisits+" WHERE F_CPERSNO=? AND TO_CHAR(VISIT_DATE,'YYYY-MM') LIKE ? ORDER BY VISIT_DATE");
	pStatement.setString(1, empPersno);  
	pStatement.setString(2, period);
	res7=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res8=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT PROJECT_NAME, TO_CHAR(MEETING_DATE, 'dd/mm/yyyy') as MD, PURPOSE FROM "+DNet.MPR_Meetings+" WHERE F_CPERSNO=? AND TO_CHAR(MEETING_DATE,'YYYY-MM') LIKE ? ORDER BY MEETING_DATE");
	pStatement.setString(1, empPersno);  
	pStatement.setString(2, period);
	res8=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res9=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT PROJECT_NAME, TO_CHAR(PDC, 'dd/mm/yyyy') AS PCD, DESCRIPTION, STATUS FROM "+DNet.MPR_WorkProgress+" WHERE F_CPERSNO=? AND TO_CHAR(WP_DATE, 'yyyy-mm') LIKE ? ORDER BY PDC");
	pStatement.setString(1, empPersno);  
	pStatement.setString(2, period);
	res9=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
ResultSet res10=null;
try {
	pStatement=dbConnection.prepareStatement("SELECT * FROM "+DNet.MPR_All+" WHERE F_CPERSNO=? AND TO_CHAR(FDATE,'YYYY-MM') LIKE ? ORDER BY FDATE", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
	pStatement.setString(1, empPersno);  
	pStatement.setString(2, period);
	res10=pStatement.executeQuery();
} catch (SQLException e) {
	e.printStackTrace();
}
int i=1;

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function update(){\r\n");
      out.write("\tdocument.getElementById('monthLabel').style.display=\"none\";\r\n");
      out.write("\tdocument.getElementById('monthInput').style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<button id='print' onclick=\"window.print()\">Print</button>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("<h1>Monthly Progress Report</h1><br>\r\n");
      out.write("<h2 class=\"dim\">(Period from - to)</h2>\r\n");
      out.write("<div style=\"align-items:center; text-align:center;cursor:pointer;\">\r\n");
      out.write("<form action=\"reportGen.jsp\" method=\"post\" id=\"reportForm\">\r\n");
      out.write("<span id=\"monthLabel\" onclick=\"update()\">");
      out.print(strPeriod );
      out.write("&nbsp;<span style=\"font-size:15px;\">&#9660;</span></span>\r\n");
      out.write("<input type=\"month\" id=\"monthInput\" name=\"month\" style=\"display:none;margin:auto;\" onchange=\"document.getElementById('reportForm').submit()\" onblur=\"document.getElementById('reportForm').submit()\" value= ");
      out.print(period );
      out.write(" required/>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<b>1)&nbsp;&nbsp;&nbsp;Name of the Personnel&nbsp;&nbsp;:</b>\r\n");
      out.write("<span>");
      out.print( empName);
      out.write("</span>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<b>2)&nbsp;&nbsp;&nbsp;Nos. of reports generated during the month with list&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"5.5%\">Sr No.</th>\r\n");
      out.write("\t\t<th width=\"37%\">Report No.</th>\r\n");
      out.write("\t\t<th width=\"17.5%\">Date</th>\r\n");
      out.write("\t\t<th width=\"40%\">Title</th>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res1!=null && res1.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res1.getString("REP_NO") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res1.getString("REPD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res1.getString("TITLE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<b>3)&nbsp;&nbsp;&nbsp;Title of research paper submitted if any&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"5.5%\">Sr No.</th>\r\n");
      out.write("\t\t<th width=\"37%\">Title of Research Paper</th>\r\n");
      out.write("\t\t<th width=\"17.5%\">Journal / Conference name</th>\r\n");
      out.write("\t\t<th width=\"40%\">Dates</th>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res2!=null && res2.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res2.getString("TITLE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res2.getString("JOUR_NAME") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res2.getString("PPD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<b>4)&nbsp;&nbsp;&nbsp;Details of CEP/Conference/Lectures attended during the month&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"8.5%\">Sr No.</th>\r\n");
      out.write("\t\t<th width=\"14.5%\">From Date</th>\r\n");
      out.write("\t\t<th width=\"14.5%\">To Date</th>\r\n");
      out.write("\t\t<th width=\"62.5%\">Title</th>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res3!=null && res3.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res3.getString("FMD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res3.getString("TOD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res3.getString("TITLE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<b>5)&nbsp;&nbsp;&nbsp;Details of TC/ any presentations you have made last&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"23%\">Date</th>\r\n");
      out.write("\t\t<th width=\"77%\">Title</th>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t\t\t\t\t");
while(res4!=null && res4.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res4.getString("TCD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res4.getString("TITLE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<b>6)&nbsp;&nbsp;&nbsp;Details of TDs during the month&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"9%\">Sr No.</th>\r\n");
      out.write("\t\t<th width=\"14.4%\">From Date</th>\r\n");
      out.write("\t\t<th width=\"14.5%\">To Date</th>\r\n");
      out.write("\t\t<th width=\"31%\">Place of visit</th>\r\n");
      out.write("\t\t<th width=\"31%\">Purpose of visit</th>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res5!=null && res5.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res5.getString("FMD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res5.getString("TOD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res5.getString("PLACE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res5.getString("PURPOSE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<b>7)&nbsp;&nbsp;&nbsp;Details of leave taken during the month&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"9%\">Sr No.</th>\r\n");
      out.write("\t\t<th width=\"22%\">From Date</th>\r\n");
      out.write("\t\t<th width=\"22%\">To Date</th>\r\n");
      out.write("\t\t<th width=\"47%\">Nature of leave</th>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res6!=null && res6.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res6.getString("FMD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res6.getString("TOD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res6.getString("LEAVE_TYPE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<b>8)&nbsp;&nbsp;&nbsp;Details of DWGs generated during the month&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"textBox\">\r\n");
      out.write("<ol>\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("DRAWING_DETAILS")){ 
      out.write("\r\n");
      out.write("<li>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("</ol>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<b>9)&nbsp;&nbsp;&nbsp;Visits to Fabrication agencies(related to hardware) during the month&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"9%\">Sr No.</th>\r\n");
      out.write("\t\t<th width=\"21%\">Name of Industry</th>\r\n");
      out.write("\t\t<th width=\"15%\">Date</th>\r\n");
      out.write("\t\t<th width=\"55%\">Purpose / Outcome</th>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res7!=null && res7.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res7.getString("INDUSTRY") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res7.getString("VISD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res7.getString("PURPOSE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<b>10)&nbsp;&nbsp;&nbsp;Details of administrative work done during the month&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"textBox\">\r\n");
      out.write("<ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("WORK_DETAILS")){ 
      out.write("\r\n");
      out.write("<li>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("</ol>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<b>11)&nbsp;&nbsp;&nbsp;Details of research work done on the topic assigned to you&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"textBox\">\r\n");
      out.write("<ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("RESEARCH")){ 
      out.write("\r\n");
      out.write("<li>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("</ol>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<b>12)&nbsp;&nbsp;&nbsp;Details of meetings attended during the month&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"7%\">Sr No.</th>\r\n");
      out.write("\t\t<th width=\"21%\">Project/Place Name</th>\r\n");
      out.write("\t\t<th width=\"15%\">Date</th>\r\n");
      out.write("\t\t<th width=\"57%\">Purpose / Outcome</th>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res8!=null && res8.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res8.getString("PROJECT_NAME") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res8.getString("MD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res8.getString("PURPOSE") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<b>13)&nbsp;&nbsp;&nbsp;Details of internal technical work review&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"textBox\">\r\n");
      out.write("<ol>\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("INT_TECH")){ 
      out.write("\r\n");
      out.write("<li>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("</ol>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<b>14)&nbsp;&nbsp;&nbsp;Details of technical work done during the month&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"textBox\">\r\n");
      out.write("<ol>\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("TECH_DETAILS")){ 
      out.write("\r\n");
      out.write("<li>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("</ol>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<b>15)&nbsp;&nbsp;&nbsp;Details of any input awaited from Project&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"textBox\">\r\n");
      out.write("<ol>\r\n");
      out.write("\t\t\t\t");
res10.beforeFirst(); 
      out.write("\r\n");
      out.write("\t\t\t\t");
while(res10.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(res10.getString("INPUT_FLAG").equals("INPUT_PROJECT")){ 
      out.write("\r\n");
      out.write("<li>");
      out.print(res10.getString("INPUT_DATA") );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("</ol>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<b>16)&nbsp;&nbsp;&nbsp;Details of work in Progress&nbsp;&nbsp;:</b>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"6.2%\">Sr No.</th>\r\n");
      out.write("\t\t<th width=\"10.6%\">Project</th>\r\n");
      out.write("\t\t<th width=\"49%\">Description</th>\r\n");
      out.write("\t\t<th width=\"18%\">Status</th>\r\n");
      out.write("\t\t<th width=\"16.2%\">PDC</th>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t");
i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
while(res9!=null && res9.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res9.getString("PROJECT_NAME") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res9.getString("DESCRIPTION") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res9.getString("STATUS") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(res9.getString("PCD") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
i++;} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
