/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-08 13:01:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BasicServlet.*;
import java.sql.*;

public final class validateLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

		String userId=request.getParameter("userId");
		String password=request.getParameter("password");
		String loginType=request.getParameter("loginType");
		DNET DNet=new DNET();
		Connection dbConnection=DNet.getSurveyThinConnection();
		Employee emp = null;
		ResultSet result;
		RequestDispatcher rd=request.getRequestDispatcher("login.jsp");
		PreparedStatement pStatement;
        try {
			pStatement=dbConnection.prepareStatement("SELECT * FROM "+DNet.Employee+" E INNER JOIN "+DNet.Passwords+" P ON E.F_CPERSNO=P.F_CPERSNO WHERE P.USERID=? AND P.PASSWORD=?");
			pStatement.setString(1,userId);
			pStatement.setString(2,password);
			result=pStatement.executeQuery();
			
			if(result.next()) {
				String persno=result.getString("f_cPersno");
				String name=result.getString("f_vc2name");
				String designation=result.getString("f_vc2designation");
				String division=result.getString("f_vc2division");
				emp=new Employee(persno,name,designation,division);
				
				HttpSession s= request.getSession(true);
				s.setAttribute("emp", emp);
				if(loginType.equals("user"))
					rd=request.getRequestDispatcher("home.jsp");
				else{
					if(persno.charAt(0)=='D')
						rd=request.getRequestDispatcher("directorHome.jsp");
					else{
						s.setAttribute("invalid", 1);
						rd=request.getRequestDispatcher("login.jsp");
					}
				}
			}
			else{
				HttpSession s= request.getSession(true);
				s.setAttribute("invalid", 1);
				rd=request.getRequestDispatcher("login.jsp");
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		dbConnection.close();
		rd.forward(request, response);
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
